# frozen_string_literal: true

module Autodns
  module DomainrobotApi
    # Represents an SSL/TLS certificate in AutoDNS
    class Certificate < BaseEntity
      def self.resource_path
        "certificate"
      end

      # Certificate product type
      def product
        attributes[:product]
      end

      # Certificate type (e.g., DV, OV, EV)
      def type
        attributes[:type]
      end

      # Common name (primary domain)
      def common_name
        attributes[:commonName] || attributes[:common_name]
      end

      # Subject alternative names (additional domains)
      def san
        attributes[:san] || attributes[:subjectAlternativeNames] || []
      end
      alias subject_alternative_names san

      # Certificate status
      def status
        attributes[:status]
      end

      # Order status
      def order_status
        attributes[:orderStatus] || attributes[:order_status]
      end

      # Certificate serial number
      def serial_number
        attributes[:serialNumber] || attributes[:serial_number]
      end

      # Validity start date
      def valid_from
        parse_datetime(attributes[:validFrom] || attributes[:valid_from])
      end

      # Validity end date
      def valid_until
        parse_datetime(attributes[:validUntil] || attributes[:valid_until] || attributes[:expire])
      end

      # Certificate data (PEM format)
      def certificate
        attributes[:certificate]
      end

      # CSR (Certificate Signing Request)
      def csr
        attributes[:csr]
      end

      # Private key (if generated by AutoDNS)
      def private_key
        attributes[:privateKey] || attributes[:private_key]
      end

      # Technical contact
      def admin_contact
        association(:adminContact, "Contact")
      end

      # Organization contact
      def org_contact
        association(:orgContact, "Contact")
      end

      # Created timestamp
      def created_at
        parse_datetime(attributes[:created])
      end

      # Updated timestamp
      def updated_at
        parse_datetime(attributes[:updated])
      end

      def to_s
        "Certificate ##{id} (#{common_name})"
      end

      private

      def parse_datetime(value)
        return nil if value.nil? || value.to_s.empty?

        DateTime.parse(value.to_s)
      rescue ArgumentError
        nil
      end
    end
  end
end
